# Generated by Django 3.1.4 on 2020-12-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssonantRhyme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('assonant_rhyme', models.CharField(max_length=10, unique=True)),
                ('amount_words', models.IntegerField(default=0)),
                ('amount_verses', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsonantRhyme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('consonant_rhyme', models.CharField(max_length=20, unique=True)),
                ('amount_words', models.IntegerField(default=0)),
                ('amount_verses', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assonant_rhyme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('word_text', models.TextField(max_length=50)),
                ('amount_verses', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('word_gender', models.CharField(choices=[('MASCULINE', 'MASC'), ('FEMENINE', 'FEM'), ('NONE', 'X')], default='X', max_length=15)),
                ('word_length', models.IntegerField(default=0)),
                ('word_type', models.CharField(choices=[('ADJECTIVE', 'ADJ'), ('PREPOSITION', 'ADP'), ('ADVERB', 'ADV'), ('VERB', 'VERB'), ('CONJUNCTION', 'CONJ'), ('DETERMINER', 'DET'), ('NOUN', 'NOUN'), ('NUMERAL', 'NUM'), ('PARTICLE', 'PRT'), ('PRONOUN', 'PRON'), ('OTHER', 'X')], default='X', max_length=15)),
                ('assonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
                ('consonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('verse_text', models.TextField()),
                ('verse_length', models.IntegerField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_beg', models.BooleanField(default=False)),
                ('is_int', models.BooleanField(default=False)),
                ('is_end', models.BooleanField(default=False)),
                ('assonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
                ('consonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme')),
                ('last_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.word')),
            ],
        ),
    ]
