# Generated by Django 3.1.3 on 2020-11-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssonantRhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assonant_rhyme', models.TextField(unique=True)),
                ('amount_words', models.IntegerField(default=0)),
                ('amount_verses', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsonantRhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consonant_rhyme', models.TextField(unique=True)),
                ('amount_words', models.IntegerField(default=0)),
                ('amount_verses', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.TextField(unique=True)),
                ('amount_verses', models.IntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
                ('consonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_text', models.TextField()),
                ('verse_cut', models.TextField(default='')),
                ('verse_length', models.IntegerField()),
                ('is_beg', models.BooleanField()),
                ('is_int', models.BooleanField()),
                ('is_end', models.BooleanField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assonant_rhyme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
                ('consonant_rhyme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme')),
                ('last_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.word')),
            ],
        ),
    ]
