# Generated by Django 3.1.2 on 2020-10-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse_text', models.TextField()),
                ('verse_length', models.IntegerField()),
                ('cons_rhy', models.TextField()),
                ('asson_rhy', models.TextField()),
                ('is_beg', models.BooleanField()),
                ('is_int', models.BooleanField()),
                ('is_end', models.BooleanField()),
            ],
        ),
    ]
