# Generated by Django 3.1.2 on 2020-10-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Verse',
        ),
    ]
