# Generated by Django 3.1.3 on 2020-11-27 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='is_beg',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='is_end',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='is_int',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='verse_cut',
        ),
        migrations.AlterField(
            model_name='verse',
            name='assonant_rhyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='consonant_rhyme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme'),
        ),
    ]
