# Generated by Django 3.1.3 on 2020-11-27 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20201127_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consonantrhyme',
            name='assonant_rhyme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme'),
        ),
    ]
