# Generated by Django 3.1.3 on 2020-11-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0003_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssonantRhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assonant_rhyme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ConsonantRhyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consonant_rhyme', models.TextField()),
                ('assonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
            ],
        ),
        migrations.AlterField(
            model_name='verse',
            name='asson_rhy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='cons_rhy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme'),
        ),
    ]
