# Generated by Django 3.1.3 on 2020-11-18 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0004_auto_20201116_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='assonantrhyme',
            name='verse_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consonantrhyme',
            name='verse_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assonantrhyme',
            name='assonant_rhyme',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='consonantrhyme',
            name='consonant_rhyme',
            field=models.TextField(unique=True),
        ),
    ]
