# Generated by Django 3.1.3 on 2020-11-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_auto_20201129_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verse',
            old_name='beg',
            new_name='is_beg',
        ),
        migrations.RenameField(
            model_name='verse',
            old_name='end',
            new_name='is_end',
        ),
        migrations.RenameField(
            model_name='verse',
            old_name='intr',
            new_name='is_int',
        ),
    ]
