# Generated by Django 3.1.3 on 2020-11-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0005_auto_20201118_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
