# Generated by Django 3.1.3 on 2020-11-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0006_verse_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assonantrhyme',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='consonantrhyme',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
