# Generated by Django 3.1.3 on 2020-11-25 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0007_auto_20201122_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assonantrhyme',
            options={'ordering': ['-verse_number', 'assonant_rhyme']},
        ),
        migrations.AlterModelOptions(
            name='consonantrhyme',
            options={'ordering': ['-verse_number', 'consonant_rhyme']},
        ),
        migrations.AddField(
            model_name='assonantrhyme',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consonantrhyme',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.TextField(unique=True)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('assonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme')),
                ('consonant_rhyme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme')),
            ],
        ),
        migrations.AddField(
            model_name='verse',
            name='last_words',
            field=models.ManyToManyField(to='poems.Word'),
        ),
    ]
