# Generated by Django 3.1.3 on 2020-11-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0009_auto_20201125_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='last_words',
        ),
        migrations.RemoveField(
            model_name='verse',
            name='last_word',
        ),
        migrations.AddField(
            model_name='verse',
            name='last_word',
            field=models.ManyToManyField(to='poems.Word'),
        ),
    ]
