# Generated by Django 3.1.3 on 2020-11-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0010_auto_20201125_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='verse_cut',
            field=models.TextField(default=''),
        ),
    ]
