# Generated by Django 3.1.3 on 2020-11-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0012_auto_20201125_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ['verse_length', 'verse_length']},
        ),
    ]
