# Generated by Django 3.1.3 on 2020-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0013_auto_20201125_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='amount_verses',
            field=models.IntegerField(default=0),
        ),
    ]
