# Generated by Django 3.1.3 on 2020-11-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0015_auto_20201125_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assonantrhyme',
            options={},
        ),
        migrations.AlterModelOptions(
            name='consonantrhyme',
            options={},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={},
        ),
    ]
