# Generated by Django 3.1.3 on 2020-11-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0016_auto_20201126_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='assonantrhyme',
            name='amount_words',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consonantrhyme',
            name='amount_words',
            field=models.IntegerField(default=0),
        ),
    ]
