# Generated by Django 3.1.3 on 2020-11-26 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0017_auto_20201126_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='assonantrhyme',
            name='amount_verses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consonantrhyme',
            name='amount_verses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verse',
            name='assonant_rhyme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.assonantrhyme'),
        ),
        migrations.AddField(
            model_name='verse',
            name='consonant_rhyme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='poems.consonantrhyme'),
        ),
    ]
